
---
apiVersion: v1
kind: Config
current-context: garden-kyma--efeaa16-external
clusters:
- name: garden-kyma--efeaa16-external
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ1ekNDQWsrZ0F3SUJBZ0lSQUtNeFhaK2w4WjBMRmY0QndjMzI3bVl3RFFZSktvWklodmNOQVFFTEJRQXcKRFRFTE1Ba0dBMVVFQXhNQ1kyRXdIaGNOTWpRd056RXdNRGN4T0RNMldoY05NelF3TnpFd01EY3hPRE0yV2pBTgpNUXN3Q1FZRFZRUURFd0pqWVRDQ0FhSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnR1BBRENDQVlvQ2dnR0JBT1o2CnR0TVRWcElEaTdLVW5aWUQwbkV4aHdJSllBdFpIZDFvSHhVV0JnenlmWDdCWHJ3SG1EeUxIODA5QWhUakVrMWgKM0doblhQbHN4TW01VmUzK2NQK0lscUUybDk2Mzg4L2dobmhjSjZtU3gvbENnWlEyQ1FKc0FpR3dhckxod1dpOQozcXNwZ3E4b21Pcm9YQXcvenRnV05xM0R1cm9vcGhCaHE0bnUrMDZhVStSZkxtV0VqY1EvRVUvZnhzNXhJejdFCmo2bWlxMUdyVFp4OEdTUExkME1CTmNaZ3hDcy9CZVA3cVZXdXBWWFBLenoweDFJN0tiUGJMRWVibEVXOWxZUzcKcWp3ekY5SjhsU2NuTSt0QW1SbjI2ZUFEQ3VUTk9lYUpSU2dRdC9kSUY1MlppTUpNSm9xN0liR0VoS25LYzRhYQozV0RxZEQySWpxYmVlTGpOak5PeWl3d2NpQzZteUh2eXIrTHRtZVZCb2dCNHUzQ3hqamFuSk5WRUdrOUVMQXdlCnczNDE0MnFhRVF6UVZZZzdweFdwMVo3ZmdWbTZMd2tBVnVOL0dEajlWSlg1MnNZcUU3RWlMeGNWTzl4d2pMcDQKNkhVVDNVc2VOaEw0OFAza2VsaVVLZEQvRXoyclpXUWNoS1B0TWN3bXlvdTRoamgrUTkxRUpsdzNGZkNwK3dJRApBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQWFZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFCkZnUVU4VVkxMHhyQkZ4Q3VEbXBuWUtFZmpXa0dWRkF3RFFZSktvWklodmNOQVFFTEJRQURnZ0dCQUVsNUNWVEIKSzk2OERaK0Z4MktNNW5FZVhFNGhweEdQSFFyeFJYZHJmalVsbDI2bHF5U3JFQWZuT2w2L3EwMkk5eE1Qa0hMSwprQVhILytZdkE1clpCNjNRQ2ZPRU82QkxtSzBsSDhZL3Yvdi9NNXdrVDN1dHhnQ3F3c0E2eXdVUXYvekhpUzFBCnZtMlRiaUhuTXAxNW1FOFZjelMyNkhCTDZOQlc2NHJMclUvK3JkTmxlQlF3YmNDRTdhTzRCNzlhT1RDYk4vMXcKWGFDNnphbDFBWlNRK0VSWVluV3VlNjhnTXpUTnZJNzg3dWp2U204dThKaGRYTWtSaEwrcDNuMFZ4MklCd2lvMwpHRDlKSXRFWHU4U0VKMStjam00MVZBejgwekRaNzdlSHErOTN6amlmNnBETVA3djNQdDNhL2lTc3ViRkNGZ3IzCjFZNlo1Z1VhN0FaNHMxZml1UmZxczI5UExHTzIxMWVxRVh3ZHlpTk9LOCt1QU1QMnBOaVRaQ29aQlpyQi9zWTcKOTZIYzRsRlpNZGdhVXUwcDBXcng1REJsczdaQTNZZXZtV3FCYVNaT0J6OXAwUEdGSDA4SmdONXptekNTUWZLcgpSOUh2VGd4Y0FVcU80dzlGWHk5QzUrNzAybEFoYmtldmVFTWUwdEVJRmNXYlF4UHl3UTZQZjQrd2h3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://api.efeaa16.kyma.ondemand.com
contexts:
- name: garden-kyma--efeaa16-external
  context:
    cluster: garden-kyma--efeaa16-external
    user: garden-kyma--efeaa16-external
users:
- name: garden-kyma--efeaa16-external
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - "--oidc-issuer-url=https://kyma.accounts.ondemand.com"
      - "--oidc-client-id=12b13a26-d993-4d0c-aa08-5f5852bbdff6"
      - "--oidc-extra-scope=email"
      - "--oidc-extra-scope=openid"
      command: kubectl-oidc_login
      installHint: |
        kubelogin plugin is required to proceed with authentication
        # Homebrew (macOS and Linux)
        brew install int128/kubelogin/kubelogin

        # Krew (macOS, Linux, Windows and ARM)
        kubectl krew install oidc-login

        # Chocolatey (Windows)
        choco install kubelogin
